name: Supuesto 2 - El Almacén de Ejecutables

# Se activa cada vez que subimos código (push)
on: push

jobs:
  generar-distribuible:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configurar Java 21
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. PERMISOS (¡Tu recordatorio!) 🛡️
      # Sin esto, Linux no deja ejecutar el wrapper de Maven
      - name: Dar permisos de ejecución a mvnw
        run: chmod +x mvnw

      # 4. GENERAR EL PAQUETE (Saltando tests)
      # -DskipTests: Le dice a Maven "No pierdas tiempo testeando, solo compila".
      # Esto hace que el build sea muchísimo más rápido.
      - name: Empaquetar aplicación (Skip Tests)
        run: ./mvnw -B package -DskipTests

      # 5. GUARDAR EL ARTEFACTO
      # Si no hacemos esto, el archivo .jar/.war se borra cuando la máquina se apaga.
      # Lo subimos a la nube de GitHub para poder descargarlo después.
      - name: Subir ejecutable a Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-final-v1  # Nombre del archivo ZIP que descargarás
          path: target/*.jar  # Ruta del archivo. (Nota: Si tu pom.xml genera .war, cambia esto a target/*.war)
          retention-days: 5   # (Opcional) Guardarlo 5 días para no llenar el espacio