name: 'Supuesto nº8: El Guardián de Secretos'

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Empaquetado e Inyección de Secretos
        # ESTA ES LA PARTE IMPORTANTE DEL EJERCICIO
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} # <--- Inyección
          DB_USER: ${{ secrets.DB_USER }}         # <--- Inyección
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          echo "La contraseña se ha inyectado correctamente en el entorno de ejecución."
          # En un entorno real, aquí el WAR ya tiene acceso a las variables