name: El Camaleón Multiplataforma

on: push

jobs:
  test-multi-os:
    # --- LA MAGIA DE LA MATRIZ ---
    strategy:
      matrix:
        # Definimos una variable llamada 'sistema_operativo' (u 'os')
        # y le damos una lista de valores.
        sistema_operativo: [ubuntu-latest, windows-latest, macos-latest]

    # Aquí usamos la variable. GitHub creará 3 trabajos paralelos:
    # 1. runs-on: ubuntu-latest
    # 2. runs-on: windows-latest
    # 3. runs-on: macos-latest
    runs-on: ${{ matrix.sistema_operativo }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

            # 3. Permisos
      - name: Dar permisos al wrapper
        run: chmod +x mvnw
        
      # NOTA IMPORTANTE:
      # En este ejercicio NO usamos el wrapper ('./mvnw') porque la sintaxis 
      # cambia entre Windows (.\mvnw) y Linux (./mvnw).
      # Para simplificar la matriz, usamos el comando 'mvn' directo, 
      # que ya viene instalado en todos los runners de GitHub.
      - name: Ejecutar Tests en ${{ matrix.sistema_operativo }}
        run: mvn -B test